# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_axi_usb2_device_0_0/DemoConfigDesign_axi_usb2_device_0_0.xci
# IP: The module: 'DemoConfigDesign_axi_usb2_device_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_axi_usb2_device_0_0/DemoConfigDesign_axi_usb2_device_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoConfigDesign_axi_usb2_device_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_axi_usb2_device_0_0/DemoConfigDesign_axi_usb2_device_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoConfigDesign_axi_usb2_device_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_axi_usb2_device_0_0/DemoConfigDesign_axi_usb2_device_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoConfigDesign_axi_usb2_device_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_axi_usb2_device_0_0/DemoConfigDesign_axi_usb2_device_0_0.xci
# IP: The module: 'DemoConfigDesign_axi_usb2_device_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_axi_usb2_device_0_0/DemoConfigDesign_axi_usb2_device_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoConfigDesign_axi_usb2_device_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_axi_usb2_device_0_0/DemoConfigDesign_axi_usb2_device_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoConfigDesign_axi_usb2_device_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_axi_usb2_device_0_0/DemoConfigDesign_axi_usb2_device_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoConfigDesign_axi_usb2_device_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
