# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_auto_pc_0/DemoInterconnect_auto_pc_0.xci
# IP: The module: 'DemoInterconnect_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_auto_pc_0/DemoInterconnect_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoInterconnect_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_auto_pc_0/DemoInterconnect_auto_pc_0.xci
# IP: The module: 'DemoInterconnect_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_auto_pc_0/DemoInterconnect_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoInterconnect_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
