# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_xbar_0/DemoConfigDesign_xbar_0.xci
# IP: The module: 'DemoConfigDesign_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_xbar_0/DemoConfigDesign_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoConfigDesign_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_xbar_0/DemoConfigDesign_xbar_0.xci
# IP: The module: 'DemoConfigDesign_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chris/OneDrive/HW_Projects/InterNoC/Codebase/InterNoC/InterNoC.srcs/sources_1/bd/DemoConfigDesign/ip/DemoConfigDesign_xbar_0/DemoConfigDesign_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoConfigDesign_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
