# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a15tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Development/FPGA/InterNoC/InterNoC.cache/wt [current_project]
set_property parent.project_path D:/Development/FPGA/InterNoC/InterNoC.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  d:/Development/FPGA/InterNoC/ip_repo/axi_native_register_space_1.0
  d:/Development/FPGA/InterNoC/ip_repo/uart_transceiver_v1_0
  d:/Development/FPGA/InterNoC/ip_repo/interface_axi_master_1.0
  d:/Development/FPGA/InterNoC/ip_repo/axi_spi_master_1.0
} [current_project]
set_property ip_output_repo d:/Development/FPGA/InterNoC/InterNoC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/hdl/DemoInterconnect_wrapper.vhd
add_files D:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/DemoInterconnect.bd
set_property used_in_implementation false [get_files -all d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_jtag_axi_0_0/constraints/jtag_axi.xdc]
set_property used_in_synthesis false [get_files -all d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_jtag_axi_0_0/constraints/DemoInterconnect_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_jtag_axi_0_0/constraints/DemoInterconnect_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_jtag_axi_0_0/DemoInterconnect_jtag_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_clk_wiz_0_0/DemoInterconnect_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_clk_wiz_0_0/DemoInterconnect_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_clk_wiz_0_0/DemoInterconnect_clk_wiz_0_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_clk_wiz_0_0/DemoInterconnect_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_mutex_0_0/DemoInterconnect_mutex_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_xbar_0/DemoInterconnect_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_auto_pc_0/DemoInterconnect_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/DemoInterconnect_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Development/FPGA/InterNoC/InterNoC.srcs/constrs_1/new/timing.xdc
set_property used_in_implementation false [get_files D:/Development/FPGA/InterNoC/InterNoC.srcs/constrs_1/new/timing.xdc]

read_xdc D:/Development/FPGA/InterNoC/InterNoC.srcs/constrs_1/new/pinout.xdc
set_property used_in_implementation false [get_files D:/Development/FPGA/InterNoC/InterNoC.srcs/constrs_1/new/pinout.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top DemoInterconnect_wrapper -part xc7a15tcpg236-1 -gated_clock_conversion auto -retiming


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DemoInterconnect_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DemoInterconnect_wrapper_utilization_synth.rpt -pb DemoInterconnect_wrapper_utilization_synth.pb"
