# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/timing.xdc

# XDC: new/pinout.xdc

# Block Designs: bd/DemoInterconnect/DemoInterconnect.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect || ORIG_REF_NAME==DemoInterconnect} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_axi_interconnect_0_0/DemoInterconnect_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_axi_interconnect_0_0 || ORIG_REF_NAME==DemoInterconnect_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_jtag_axi_0_0/DemoInterconnect_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_jtag_axi_0_0 || ORIG_REF_NAME==DemoInterconnect_jtag_axi_0_0} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_clk_wiz_0_0/DemoInterconnect_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_clk_wiz_0_0 || ORIG_REF_NAME==DemoInterconnect_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_uart_transceiver_0_0/DemoInterconnect_uart_transceiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_uart_transceiver_0_0 || ORIG_REF_NAME==DemoInterconnect_uart_transceiver_0_0} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_uart_transceiver_0_1/DemoInterconnect_uart_transceiver_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_uart_transceiver_0_1 || ORIG_REF_NAME==DemoInterconnect_uart_transceiver_0_1} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_axi_spi_master_0_0/DemoInterconnect_axi_spi_master_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_axi_spi_master_0_0 || ORIG_REF_NAME==DemoInterconnect_axi_spi_master_0_0} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_axi_spi_master_0_1/DemoInterconnect_axi_spi_master_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_axi_spi_master_0_1 || ORIG_REF_NAME==DemoInterconnect_axi_spi_master_0_1} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_axi_spi_master_1_0/DemoInterconnect_axi_spi_master_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_axi_spi_master_1_0 || ORIG_REF_NAME==DemoInterconnect_axi_spi_master_1_0} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_axi_spi_master_1_1/DemoInterconnect_axi_spi_master_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_axi_spi_master_1_1 || ORIG_REF_NAME==DemoInterconnect_axi_spi_master_1_1} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_mutex_0_0/DemoInterconnect_mutex_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_mutex_0_0 || ORIG_REF_NAME==DemoInterconnect_mutex_0_0} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_xbar_0/DemoInterconnect_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_xbar_0 || ORIG_REF_NAME==DemoInterconnect_xbar_0} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_ila_0_0/DemoInterconnect_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_ila_0_0 || ORIG_REF_NAME==DemoInterconnect_ila_0_0} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_internoc_ni_axi_master_0_0/DemoInterconnect_internoc_ni_axi_master_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_internoc_ni_axi_master_0_0 || ORIG_REF_NAME==DemoInterconnect_internoc_ni_axi_master_0_0} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_internoc_ni_axi_master_1_0/DemoInterconnect_internoc_ni_axi_master_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_internoc_ni_axi_master_1_0 || ORIG_REF_NAME==DemoInterconnect_internoc_ni_axi_master_1_0} -quiet] -quiet

# IP: bd/DemoInterconnect/ip/DemoInterconnect_auto_pc_0/DemoInterconnect_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DemoInterconnect_auto_pc_0 || ORIG_REF_NAME==DemoInterconnect_auto_pc_0} -quiet] -quiet

# XDC: bd/DemoInterconnect/DemoInterconnect_ooc.xdc
