webtalk_init -webtalk_dir D:/Development/FPGA/InterNoC/InterNoC.sim/sim_1/behav/xsim.dir/DemoInterconnect_TestBench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 04 19:16:34 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1756540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "179506251_1777502996_210618150_129" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "48d6f4b88c2959b3898c095377c29e3c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4ebeb462c0a04df2b446b34cb2a23969" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "112" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-6300 Six-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3516 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "551325500 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "13.34_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "20768_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3920584624 -regid "179506251_1777502996_210618150_129" -xml D:/Development/FPGA/InterNoC/InterNoC.sim/sim_1/behav/xsim.dir/DemoInterconnect_TestBench_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Development/FPGA/InterNoC/InterNoC.sim/sim_1/behav/xsim.dir/DemoInterconnect_TestBench_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Development/FPGA/InterNoC/InterNoC.sim/sim_1/behav/xsim.dir/DemoInterconnect_TestBench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
