# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_axi_quad_spi_0_1/DemoInterconnect_axi_quad_spi_0_1.xci
# IP: The module: 'DemoInterconnect_axi_quad_spi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_axi_quad_spi_0_1/DemoInterconnect_axi_quad_spi_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoInterconnect_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_axi_quad_spi_0_1/DemoInterconnect_axi_quad_spi_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoInterconnect_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_axi_quad_spi_0_1/DemoInterconnect_axi_quad_spi_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoInterconnect_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_axi_quad_spi_0_1/DemoInterconnect_axi_quad_spi_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoInterconnect_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_axi_quad_spi_0_1/DemoInterconnect_axi_quad_spi_0_1.xci
# IP: The module: 'DemoInterconnect_axi_quad_spi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_axi_quad_spi_0_1/DemoInterconnect_axi_quad_spi_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoInterconnect_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_axi_quad_spi_0_1/DemoInterconnect_axi_quad_spi_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoInterconnect_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_axi_quad_spi_0_1/DemoInterconnect_axi_quad_spi_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoInterconnect_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Development/FPGA/InterNoC/InterNoC.srcs/sources_1/bd/DemoInterconnect/ip/DemoInterconnect_axi_quad_spi_0_1/DemoInterconnect_axi_quad_spi_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'DemoInterconnect_axi_quad_spi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
